import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'
import AImegleImage from '../public/OIG.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-white h-[6rem] flex items-center shadow-md ring-1 ring-inset ring-gray-400 px-6 justify-center sm:justify-between'>
          <div className='flex items-center'>
            <Image src={AImegleImage} className='h-[4.8rem] w-[4.8rem] rounded-[.5rem] zoom-in-[2]' />
            <h1 className='px-3 text-[3.8rem] font-black text-orange-400'>AImegle</h1>
            <h2 className='ml-[2rem] xl:ml-[6rem] font-black text-[1.6rem] -skew-y-3 hidden lg:inline-block'>Talk to automated strangers!</h2>
          </div>

          <div>
            <h2 className='text-2xl text-sky-300 hidden sm:inline-block'>
              <span className='font-bold text-4xl'>Ꝏ+</span> online now
            </h2>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
